//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.17 at 10:10:29 PM PKT 
//


package com.lajpat.guides.music;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mood.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="mood"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Happy"/&gt;
 *     &lt;enumeration value="Sad"/&gt;
 *     &lt;enumeration value="Relaxing"/&gt;
 *     &lt;enumeration value="Energetic"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "mood")
@XmlEnum
public enum Mood {

    @XmlEnumValue("Happy")
    HAPPY("Happy"),
    @XmlEnumValue("Sad")
    SAD("Sad"),
    @XmlEnumValue("Relaxing")
    RELAXING("Relaxing"),
    @XmlEnumValue("Energetic")
    ENERGETIC("Energetic");
    private final String value;

    Mood(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Mood fromValue(String v) {
        for (Mood c: Mood.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
