//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.17 at 10:10:29 PM PKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://lajpat.com/guides/music", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.lajpat.guides.music;
